package repositories

var LanguagesData = []LingroLanguages{
	{ ID: 1, Language: "af", Name: "Afrikaans" },
	{ ID: 2, Language: "sq", Name: "Albanian" },
	{ ID: 3, Language: "am", Name: "Amharic" },
	{ ID: 4, Language: "ar", Name: "Arabic" },
	{ ID: 5, Language: "hy", Name: "Armenian" },
	{ ID: 6, Language: "az", Name: "Azerbaijani" },
	{ ID: 7, Language: "eu", Name: "Basque" },
	{ ID: 8, Language: "be", Name: "Belarusian" },
	{ ID: 9, Language: "bn", Name: "Bengali" },
	{ ID: 10, Language: "bs", Name: "Bosnian" },
	{ ID: 11, Language: "bg", Name: "Bulgarian" },
	{ ID: 12, Language: "ca", Name: "Catalan" },
	{ ID: 13, Language: "ceb", Name: "Cebuano" },
	{ ID: 14, Language: "zh-CN", Name: "Chinese (Simplified)" },
	{ ID: 15, Language: "zh-TW", Name: "Chinese (Traditional)" },
	{ ID: 16, Language: "co", Name: "Corsican" },
	{ ID: 17, Language: "hr", Name: "Croatian" },
	{ ID: 18, Language: "cs", Name: "Czech" },
	{ ID: 19, Language: "da", Name: "Danish" },
	{ ID: 20, Language: "nl", Name: "Dutch" },
	{ ID: 21, Language: "en", Name: "English" },
	{ ID: 22, Language: "eo", Name: "Esperanto" },
	{ ID: 23, Language: "et", Name: "Estonian" },
	{ ID: 24, Language: "fi", Name: "Finnish" },
	{ ID: 25, Language: "fr", Name: "French" },
	{ ID: 26, Language: "fy", Name: "Frisian" },
	{ ID: 27, Language: "gl", Name: "Galician" },
	{ ID: 28, Language: "ka", Name: "Georgian" },
	{ ID: 29, Language: "de", Name: "German" },
	{ ID: 30, Language: "el", Name: "Greek" },
	{ ID: 31, Language: "gu", Name: "Gujarati" },
	{ ID: 32, Language: "ht", Name: "Haitian Creole" },
	{ ID: 33, Language: "ha", Name: "Hausa" },
	{ ID: 34, Language: "haw", Name: "Hawaiian" },
	{ ID: 35, Language: "he", Name: "Hebrew" },
	{ ID: 36, Language: "hi", Name: "Hindi" },
	{ ID: 37, Language: "hmn", Name: "Hmong" },
	{ ID: 38, Language: "hu", Name: "Hungarian" },
	{ ID: 39, Language: "is", Name: "Icelandic" },
	{ ID: 40, Language: "ig", Name: "Igbo" },
	{ ID: 41, Language: "id", Name: "Indonesian" },
	{ ID: 42, Language: "ga", Name: "Irish" },
	{ ID: 43, Language: "it", Name: "Italian" },
	{ ID: 44, Language: "ja", Name: "Japanese" },
	{ ID: 45, Language: "jv", Name: "Javanese" },
	{ ID: 46, Language: "kn", Name: "Kannada" },
	{ ID: 47, Language: "kk", Name: "Kazakh" },
	{ ID: 48, Language: "km", Name: "Khmer" },
	{ ID: 49, Language: "rw", Name: "Kinyarwanda" },
	{ ID: 50, Language: "ko", Name: "Korean" },
	{ ID: 51, Language: "ku", Name: "Kurdish" },
	{ ID: 52, Language: "ky", Name: "Kyrgyz" },
	{ ID: 53, Language: "lo", Name: "Lao" },
	{ ID: 54, Language: "la", Name: "Latin" },
	{ ID: 55, Language: "lv", Name: "Latvian" },
	{ ID: 56, Language: "lt", Name: "Lithuanian" },
	{ ID: 57, Language: "lb", Name: "Luxembourgish" },
	{ ID: 58, Language: "mk", Name: "Macedonian" },
	{ ID: 59, Language: "mg", Name: "Malagasy" },
	{ ID: 60, Language: "ms", Name: "Malay" },
	{ ID: 61, Language: "ml", Name: "Malayalam" },
	{ ID: 62, Language: "mt", Name: "Maltese" },
	{ ID: 63, Language: "mi", Name: "Maori" },
	{ ID: 64, Language: "mr", Name: "Marathi" },
	{ ID: 65, Language: "mn", Name: "Mongolian" },
	{ ID: 66, Language: "my", Name: "Myanmar (Burmese)" },
	{ ID: 67, Language: "ne", Name: "Nepali" },
	{ ID: 68, Language: "no", Name: "Norwegian" },
	{ ID: 69, Language: "ny", Name: "Nyanja (Chichewa)" },
	{ ID: 70, Language: "or", Name: "Odia (Oriya)" },
	{ ID: 71, Language: "ps", Name: "Pashto" },
	{ ID: 72, Language: "fa", Name: "Persian" },
	{ ID: 73, Language: "pl", Name: "Polish" },
	{ ID: 74, Language: "pt", Name: "Portuguese" },
	{ ID: 75, Language: "pa", Name: "Punjabi" },
	{ ID: 76, Language: "ro", Name: "Romanian" },
	{ ID: 77, Language: "ru", Name: "Russian" },
	{ ID: 78, Language: "sm", Name: "Samoan" },
	{ ID: 79, Language: "gd", Name: "Scots Gaelic" },
	{ ID: 80, Language: "sr", Name: "Serbian" },
	{ ID: 81, Language: "st", Name: "Sesotho" },
	{ ID: 82, Language: "sn", Name: "Shona" },
	{ ID: 83, Language: "sd", Name: "Sindhi" },
	{ ID: 84, Language: "si", Name: "Sinhala (Sinhalese)" },
	{ ID: 85, Language: "sk", Name: "Slovak" },
	{ ID: 86, Language: "sl", Name: "Slovenian" },
	{ ID: 87, Language: "so", Name: "Somali" },
	{ ID: 88, Language: "es", Name: "Spanish" },
	{ ID: 89, Language: "su", Name: "Sundanese" },
	{ ID: 90, Language: "sw", Name: "Swahili" },
	{ ID: 91, Language: "sv", Name: "Swedish" },
	{ ID: 92, Language: "tl", Name: "Tagalog (Filipino)" },
	{ ID: 93, Language: "tg", Name: "Tajik" },
	{ ID: 94, Language: "ta", Name: "Tamil" },
	{ ID: 95, Language: "tt", Name: "Tatar" },
	{ ID: 96, Language: "te", Name: "Telugu" },
	{ ID: 97, Language: "th", Name: "Thai" },
	{ ID: 98, Language: "tr", Name: "Turkish" },
	{ ID: 99, Language: "tk", Name: "Turkmen" },
	{ ID: 100, Language: "uk", Name: "Ukrainian" },
	{ ID: 101, Language: "ur", Name: "Urdu" },
	{ ID: 102, Language: "ug", Name: "Uyghur" },
	{ ID: 103, Language: "uz", Name: "Uzbek" },
	{ ID: 104, Language: "vi", Name: "Vietnamese" },
	{ ID: 105, Language: "cy", Name: "Welsh" },
	{ ID: 106, Language: "xh", Name: "Xhosa" },
	{ ID: 107, Language: "yi", Name: "Yiddish" },
	{ ID: 108, Language: "yo", Name: "Yoruba" },
	{ ID: 109, Language: "zu", Name: "Zulu" },
}

func (r *LingroLanguagesRepository) InitLanguages() error {
	var count int64
	r.db.Model(&LingroLanguages{}).Count(&count)

	if count == 0 {
		result := r.db.Create(&LanguagesData)
		return result.Error
	}

	return nil
}