package repositories

var LanguagesData = []LingroLanguages{
	{Language: "af", Name: "Afrikaans"},
	{Language: "sq", Name: "Albanian"},
	{Language: "am", Name: "Amharic"},
	{Language: "ar", Name: "Arabic"},
	{Language: "hy", Name: "Armenian"},
	{Language: "az", Name: "Azerbaijani"},
	{Language: "eu", Name: "Basque"},
	{Language: "be", Name: "Belarusian"},
	{Language: "bn", Name: "Bengali"},
	{Language: "bs", Name: "Bosnian"},
	{Language: "bg", Name: "Bulgarian"},
	{Language: "ca", Name: "Catalan"},
	{Language: "ceb", Name: "Cebuano"},
	{Language: "zh-CN", Name: "Chinese (Simplified)"},
	{Language: "zh-TW", Name: "Chinese (Traditional)"},
	{Language: "co", Name: "Corsican"},
	{Language: "hr", Name: "Croatian"},
	{Language: "cs", Name: "Czech"},
	{Language: "da", Name: "Danish"},
	{Language: "nl", Name: "Dutch"},
	{Language: "en", Name: "English"},
	{Language: "eo", Name: "Esperanto"},
	{Language: "et", Name: "Estonian"},
	{Language: "fi", Name: "Finnish"},
	{Language: "fr", Name: "French"},
	{Language: "fy", Name: "Frisian"},
	{Language: "gl", Name: "Galician"},
	{Language: "ka", Name: "Georgian"},
	{Language: "de", Name: "German"},
	{Language: "el", Name: "Greek"},
	{Language: "gu", Name: "Gujarati"},
	{Language: "ht", Name: "Haitian Creole"},
	{Language: "ha", Name: "Hausa"},
	{Language: "haw", Name: "Hawaiian"},
	{Language: "he", Name: "Hebrew"},
	{Language: "hi", Name: "Hindi"},
	{Language: "hmn", Name: "Hmong"},
	{Language: "hu", Name: "Hungarian"},
	{Language: "is", Name: "Icelandic"},
	{Language: "ig", Name: "Igbo"},
	{Language: "id", Name: "Indonesian"},
	{Language: "ga", Name: "Irish"},
	{Language: "it", Name: "Italian"},
	{Language: "ja", Name: "Japanese"},
	{Language: "jv", Name: "Javanese"},
	{Language: "kn", Name: "Kannada"},
	{Language: "kk", Name: "Kazakh"},
	{Language: "km", Name: "Khmer"},
	{Language: "rw", Name: "Kinyarwanda"},
	{Language: "ko", Name: "Korean"},
	{Language: "ku", Name: "Kurdish"},
	{Language: "ky", Name: "Kyrgyz"},
	{Language: "lo", Name: "Lao"},
	{Language: "la", Name: "Latin"},
	{Language: "lv", Name: "Latvian"},
	{Language: "lt", Name: "Lithuanian"},
	{Language: "lb", Name: "Luxembourgish"},
	{Language: "mk", Name: "Macedonian"},
	{Language: "mg", Name: "Malagasy"},
	{Language: "ms", Name: "Malay"},
	{Language: "ml", Name: "Malayalam"},
	{Language: "mt", Name: "Maltese"},
	{Language: "mi", Name: "Maori"},
	{Language: "mr", Name: "Marathi"},
	{Language: "mn", Name: "Mongolian"},
	{Language: "my", Name: "Myanmar (Burmese)"},
	{Language: "ne", Name: "Nepali"},
	{Language: "no", Name: "Norwegian"},
	{Language: "ny", Name: "Nyanja (Chichewa)"},
	{Language: "or", Name: "Odia (Oriya)"},
	{Language: "ps", Name: "Pashto"},
	{Language: "fa", Name: "Persian"},
	{Language: "pl", Name: "Polish"},
	{Language: "pt", Name: "Portuguese"},
	{Language: "pa", Name: "Punjabi"},
	{Language: "ro", Name: "Romanian"},
	{Language: "ru", Name: "Russian"},
	{Language: "sm", Name: "Samoan"},
	{Language: "gd", Name: "Scots Gaelic"},
	{Language: "sr", Name: "Serbian"},
	{Language: "st", Name: "Sesotho"},
	{Language: "sn", Name: "Shona"},
	{Language: "sd", Name: "Sindhi"},
	{Language: "si", Name: "Sinhala (Sinhalese)"},
	{Language: "sk", Name: "Slovak"},
	{Language: "sl", Name: "Slovenian"},
	{Language: "so", Name: "Somali"},
	{Language: "es", Name: "Spanish"},
	{Language: "su", Name: "Sundanese"},
	{Language: "sw", Name: "Swahili"},
	{Language: "sv", Name: "Swedish"},
	{Language: "tl", Name: "Tagalog (Filipino)"},
	{Language: "tg", Name: "Tajik"},
	{Language: "ta", Name: "Tamil"},
	{Language: "tt", Name: "Tatar"},
	{Language: "te", Name: "Telugu"},
	{Language: "th", Name: "Thai"},
	{Language: "tr", Name: "Turkish"},
	{Language: "tk", Name: "Turkmen"},
	{Language: "uk", Name: "Ukrainian"},
	{Language: "ur", Name: "Urdu"},
	{Language: "ug", Name: "Uyghur"},
	{Language: "uz", Name: "Uzbek"},
	{Language: "vi", Name: "Vietnamese"},
	{Language: "cy", Name: "Welsh"},
	{Language: "xh", Name: "Xhosa"},
	{Language: "yi", Name: "Yiddish"},
	{Language: "yo", Name: "Yoruba"},
	{Language: "zu", Name: "Zulu"},
}

func (r *LingroLanguagesRepository) InitLanguages() error {
	var count int64
	r.db.Model(&LingroLanguages{}).Count(&count)

	if count == 0 {
		result := r.db.Create(&LanguagesData)
		return result.Error
	}

	return nil
}